# Generated by Django 2.1.4 on 2019-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('parent_hash', models.CharField(max_length=255, unique=True)),
                ('nonce', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('difficulty', models.CharField(max_length=255)),
                ('total_difficulty', models.CharField(max_length=255)),
                ('gas_limit', models.IntegerField()),
                ('gas_used', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('miner', models.CharField(max_length=128)),
                ('extra_data', models.CharField(max_length=1024)),
                ('logs_bloom', models.CharField(max_length=2048)),
                ('mix_hash', models.CharField(max_length=255)),
                ('receipts_root', models.CharField(max_length=255)),
                ('seal_fields', models.CharField(max_length=1024)),
                ('sha3_uncles', models.CharField(max_length=255)),
                ('state_root', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('transactions_root', models.CharField(max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hash', models.CharField(max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
