# Generated by Django 2.1.4 on 2019-01-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Blocks')),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=32)),
                ('nonce', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('gas_price', models.DecimalField(decimal_places=18, max_digits=36)),
                ('input', models.TextField(max_length=255)),
                ('chain_id', models.CharField(max_length=4, null=True)),
                ('condition', models.CharField(max_length=255, null=True)),
                ('creates', models.CharField(max_length=255, null=True)),
                ('public_key', models.CharField(max_length=1024)),
                ('raw', models.TextField(max_length=2048)),
                ('transaction_index', models.CharField(max_length=4)),
                ('standard_v', models.CharField(max_length=4)),
                ('r', models.CharField(max_length=255)),
                ('v', models.CharField(max_length=8)),
                ('s', models.CharField(max_length=4096)),

            ],
        ),
    ]
    dependencies = [
        ('api', '0001_initial'),
    ]

